openapi: 3.0.3
info:
  title: Choreo Sample - Get hello project - Nodejs REST API Service
  description: >-
    This is a simple service that when using a GET method says, "Hello World
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:8080
tags:
  - name: hello
    description: 
paths:
  /books:
    summary: Says Hello World
    get:
      summary: Says Hello World
      operationId: SayHello
      tags:
        - hello
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/String"
   
